name: Release cv pdf

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cv/latex/**"
      - ".github/workflows/release_cv.yaml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cv

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build EN CV from latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Dmitry_Moskalenko_CV.tex
          working_directory: cv/latex/en

      - name: Build RU CV from latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Dmitry_Moskalenko_CV.tex
          working_directory: cv/latex/ru

      - name: Move pdf files to pdf dir
        run: |
          rm pdf/en/Dmitry_Moskalenko_CV.pdf
          rm pdf/ru/Dmitry_Moskalenko_CV.pdf
          mv latex/en/Dmitry_Moskalenko_CV.pdf pdf/en/Dmitry_Moskalenko_CV.pdf
          mv latex/ru/Dmitry_Moskalenko_CV.pdf pdf/ru/Dmitry_Moskalenko_CV.pdf

      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: |
            cv/pdf/en/Dmitry_Moskalenko_CV.pdf
            cv/pdf/ru/Dmitry_Moskalenko_CV.pdf
          commit-msg: "chore: update cv pdf files"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-removing: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: cv/pdf

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cv

      - name: Rename cv files
        run: |
          mv en/Dmitry_Moskalenko_CV.pdf en/Dmitry_Moskalenko_CV_EN.pdf
          mv ru/Dmitry_Moskalenko_CV.pdf ru/Dmitry_Moskalenko_CV_RU.pdf

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          tag_template: "yyyy.mm.dd.i"

      - name: Upload cv to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            en/Dmitry_Moskalenko_CV_EN.pdf
            ru/Dmitry_Moskalenko_CV_RU.pdf
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: CV ${{ steps.generate_release_tag.outputs.next_release_tag }}
